name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java with Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'  
        maven-version: '3.9.2'  
        distribution: 'temurin'  

    - name: Increment version
      run: |
        VERSION=$(grep -oP '(?<=<version>).*?(?=</version>)' pom.xml | head -n 1)
        NEW_VERSION=$(echo $VERSION | awk -F. '{print $1 "." $2 "." $3+1}')
        sed -i "0,/<version>${VERSION}<\/version>/s|<version>.*</version>|<version>${NEW_VERSION}</version>|" pom.xml
        git config user.name "linor.ronen"
        git config user.email "linor.ronen@gmail.com"
        git commit -am "Increment patch version to $NEW_VERSION"
        git push origin master  

    - name: Build JAR
      run: mvn clean package

    - name: Build Docker Image
      run: |
        docker build -t linorg/simple-java-maven-app:${NEW_VERSION} .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u linorg --password-stdin
        docker push linorg/simple-java-maven-app:${NEW_VERSION}
